language: generic

sudo: required

os:
  - linux

dist: trusty

branches:
  only: master

before_script:
  - bash ./test/test_prerequisites.sh

script:
  - ./install.sh --all-yes

after_success:
  - bash ./test/check_travis_result.sh